checks = [
  "all",
  "-ST1021", # "comment on exported type PointerEvent should be of the form "<name> ..." (with optional leading article)"
  "-ST1000", # "package comment should be of the form 'Package <name>...'"
  "-ST1006" # "don't use generic names such as "this"..."
]
