# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# actions/deploy-pages.
permissions:
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Install Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 24.4.1
          cache: npm
      - name: Install Dependencies
        run: npm ci --no-fund
      - name: Lint
        run: npx lint
      - name: Build
        run: npx tsc --build
      - name: Unit Test
        run: npm run test:unit
      - name: Upload schema/
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: schema/

  deploy:
    environment:
      name: github-pages
    # skip PRs.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/deploy-pages@v4.0.5









can github just run post install script?



name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: |
          curl --silent --location https://github.com/tinygo-org/tinygo/releases/download/v0.40.1/tinygo_0.40.1_amd64.deb --output /tmp/tinygo.deb
          sudo dpkg --install /tmp/tinygo.deb
          curl --silent --location https://github.com/watchexec/watchexec/releases/download/v2.3.2/watchexec-2.3.2-x86_64-unknown-linux-musl.deb --output /tmp/watchexec.deb
          sudo dpkg --install /tmp/watchexec.deb
          mkdir --parents "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          curl --silent --location https://github.com/WebAssembly/binaryen/releases/download/version_120/binaryen-version_120-x86_64-linux.tar.gz | tar --extract --gzip --directory="$HOME/bin/" --strip-components=2 --wildcards '*/bin/wasm-opt'
          npm ci

      - name: Test Formatting
        run: make test-fmt
      - name: Lint Go
        run: make lint-go
      - name: Lint JS
        run: make lint-js
      - name: Test Go
        run: make test-go
      - name: Test JS
        run: make test-js
      - name: Build
        run: make build
      - name: Test Filesizes
        run: make fat-check
