export type ClockSchema = object
export type CollideToggleSchema = object
export type MouseStatusSchema = object
export type RenderToggleSchema = object
export type RotateSchema = {speed: number}
export type SoundToggleSchema = object
export type ScreenshotButtonSchema = object
export type TallySchema = object
export type SuperballSchema = object
export type SuperballButtonSchema = object
